"""Decision engine for determining review strategy"""

import re
from dataclasses import dataclass
from enum import Enum

from bot.config import Config
from bot.diff_parser import ParsedDiff, estimate_tokens


class Action(Enum):
    SKIP = "skip"
    OPENROUTER = "openrouter"
    GROQ = "groq"
    GEMINI = "gemini"


@dataclass
class ReviewDecision:
    action: Action
    reason: str
    confidence: float = 1.0
    skip_category: str | None = None


@dataclass
class FileMetrics:
    path: str
    tokens: int


@dataclass
class PRMetrics:
    total_tokens: int
    max_file_tokens: int
    file_count: int
    file_tokens: dict[str, int]
    extra_chars: int = 0

    @property
    def effective_tokens(self) -> int:
        return self.total_tokens + self.extra_chars // 4


class DecisionEngine:

    DOCS_PATTERNS = [
        r"\.md$",
        r"\.rst$",
        r"\.txt$",
        r"docs?/",
        r"documentation/",
        r"CHANGELOG",
        r"LICENSE",
        r"README",
    ]

    DEPS_PATTERNS = [
        r"package-lock\.json$",
        r"yarn\.lock$",
        r"poetry\.lock$",
        r"pipfile\.lock$",
        r"requirements\.txt$",
        r"Gemfile\.lock$",
        r"Cargo\.lock$",
        r"go\.mod$",
        r"go\.sum$",
        r"\.gemspec$",
        r"pubspec\.yaml$",
        r"Podfile\.lock$",
        r"composer\.lock$",
    ]

    # Machine-generated files. Deliberately narrower than DEPS_PATTERNS: a
    # human edits requirements.txt, go.mod and package.json, so a change there
    # is a real dependency decision worth reviewing. Nobody hand-writes a
    # lockfile, a minified bundle or a committed snapshot.
    #
    # These are already in DEPS_PATTERNS, but _is_deps_only only fires when
    # *every* changed file matches. A lockfile committed alongside real source
    # rode into the review as ordinary code, and the model read line 1 of
    # poetry.lock ("generated by Poetry 2.2.1") as a dependency downgrade.
    GENERATED_PATTERNS = [
        r"package-lock\.json$",
        r"yarn\.lock$",
        r"pnpm-lock\.yaml$",
        r"poetry\.lock$",
        r"Pipfile\.lock$",
        r"Gemfile\.lock$",
        r"Cargo\.lock$",
        r"composer\.lock$",
        r"Podfile\.lock$",
        r"go\.sum$",
        r"\.min\.(js|css)$",
        r"\.map$",
        r"__snapshots__/",
        r"\.snap$",
        r"(^|/)vendor/",
        r"(^|/)node_modules/",
        r"\.pb\.go$",
        r"_pb2(_grpc)?\.py$",
        r"\.generated\.\w+$",
    ]

    TEST_PATTERNS = [
        r"_test\.py$",
        r"_tests\.py$",
        r"test_.*\.py$",
        r".*_test\.go$",
        r".*_test\.js$",
        r".*_test\.ts$",
        r".*\.spec\.(js|ts)$",
        r".*\.test\.(js|ts)$",
        r"__tests__/",
        r"/tests/",
    ]

    def __init__(self, config: Config):
        self.config = config

    def decide(self, diff: ParsedDiff, extra_chars: int = 0) -> ReviewDecision:
        if not self.config.sorge.get("enabled", True):
            return ReviewDecision(
                action=Action.SKIP,
                reason="Sorge is disabled in config",
                skip_category="disabled"
            )

        if self._is_docs_only(diff):
            return ReviewDecision(
                action=Action.SKIP,
                reason="Docs-only changes - no review needed",
                skip_category="docs"
            )

        if self.config.filters.skip_deps and self._is_deps_only(diff):
            return ReviewDecision(
                action=Action.SKIP,
                reason="Dependency changes only - no review needed",
                skip_category="deps"
            )

        if self.config.filters.skip_tests and self._is_tests_only(diff):
            return ReviewDecision(
                action=Action.SKIP,
                reason="Test-only changes - no review needed",
                skip_category="tests"
            )

        total_lines = diff.lines_added + diff.lines_deleted

        if total_lines < self.config.filters.min_lines:
            return ReviewDecision(
                action=Action.SKIP,
                reason=f"Too few lines changed ({total_lines} < {self.config.filters.min_lines})",
                skip_category="too_small"
            )

        estimated_tokens = self._estimate_tokens(diff, extra_chars)

        groq_enabled = bool(self.config.groq.enabled)
        openrouter_enabled = bool(self.config.openrouter.enabled)
        gemini_enabled = bool(self.config.gemini.enabled)

        small_t = self.config.routing.small_pr_threshold
        medium_t = self.config.routing.medium_pr_threshold
        large_t = self.config.routing.large_pr_threshold

        return self._route_by_tier(
            estimated_tokens=estimated_tokens,
            groq_enabled=groq_enabled,
            openrouter_enabled=openrouter_enabled,
            gemini_enabled=gemini_enabled,
            small_t=small_t,
            medium_t=medium_t,
            large_t=large_t,
        )

    def get_preference_chain(
        self,
        estimated_tokens: int,
    ) -> list[tuple[Action, bool]]:
        """Return the ordered preference chain for a given token estimate.
        
        Used both for initial routing and for runtime provider failover.
        Groq is excluded from medium/large tiers (32K window too small).
        """
        groq_enabled = bool(self.config.groq.enabled)
        openrouter_enabled = bool(self.config.openrouter.enabled)
        gemini_enabled = bool(self.config.gemini.enabled)
        small_t = self.config.routing.small_pr_threshold
        medium_t = self.config.routing.medium_pr_threshold
        large_t = self.config.routing.large_pr_threshold

        if estimated_tokens <= small_t:
            return [
                (Action.GROQ, groq_enabled),
                (Action.OPENROUTER, openrouter_enabled),
                (Action.GEMINI, gemini_enabled),
            ]
        elif estimated_tokens > large_t:
            return [
                (Action.GEMINI, gemini_enabled),
                (Action.OPENROUTER, openrouter_enabled),
            ]
        elif estimated_tokens <= medium_t:
            return [
                (Action.OPENROUTER, openrouter_enabled),
                (Action.GEMINI, gemini_enabled),
            ]
        else:
            return [
                (Action.GEMINI, gemini_enabled),
                (Action.OPENROUTER, openrouter_enabled),
            ]

    def _route_by_tier(
        self,
        *,
        estimated_tokens: int,
        groq_enabled: bool,
        openrouter_enabled: bool,
        gemini_enabled: bool,
        small_t: int,
        medium_t: int,
        large_t: int,
    ) -> ReviewDecision:
        chain = self.get_preference_chain(estimated_tokens)

        # Determine tier label for logging
        if estimated_tokens <= small_t:
            tier = "small"
        elif estimated_tokens > large_t:
            tier = "large"
        elif estimated_tokens <= medium_t:
            tier = "medium"
        else:
            tier = "between-medium-large"

        for action, enabled in chain:
            if enabled:
                confidence = 0.95 if tier in ("small", "medium", "large") else 0.85
                return ReviewDecision(
                    action=action,
                    reason=f"{tier} diff (~{estimated_tokens} tokens) - using {action.value}",
                    confidence=confidence,
                )

        return ReviewDecision(
            action=Action.SKIP,
            reason="No review provider enabled",
            skip_category="no_provider",
        )

    def _estimate_tokens(self, diff: ParsedDiff, extra_chars: int = 0) -> int:
        return estimate_tokens(diff.raw) + extra_chars // 4

    def compute_metrics(self, diff: ParsedDiff, extra_chars: int = 0) -> PRMetrics:
        file_tokens: dict[str, int] = {}
        max_file = 0

        for path, change in diff.file_changes.items():
            tokens = estimate_tokens(change.raw_diff) if change.raw_diff else 0
            file_tokens[path] = tokens
            max_file = max(max_file, tokens)

        if not file_tokens and diff.raw:
            file_tokens["__whole__"] = estimate_tokens(diff.raw)
            max_file = file_tokens["__whole__"]

        return PRMetrics(
            total_tokens=estimate_tokens(diff.raw),
            max_file_tokens=max_file,
            file_count=len(diff.files),
            file_tokens=file_tokens,
            extra_chars=extra_chars,
        )

    def _matches_any_pattern(self, filename: str, patterns: list[str], flags: int = 0) -> bool:
        return any(re.search(p, filename, flags) for p in patterns)

    def _is_docs_only(self, diff: ParsedDiff) -> bool:
        if not self.config.filters.skip_docs or not diff.files:
            return False
        return all(self._matches_any_pattern(f, self.DOCS_PATTERNS, re.IGNORECASE) for f in diff.files)

    def _is_deps_only(self, diff: ParsedDiff) -> bool:
        if not diff.files:
            return False
        return all(self._matches_any_pattern(f, self.DEPS_PATTERNS) for f in diff.files)

    def is_generated(self, path: str) -> bool:
        return self._matches_any_pattern(path, self.GENERATED_PATTERNS, re.IGNORECASE)

    def strip_generated_files(self, diff: ParsedDiff) -> tuple[ParsedDiff, list[str]]:
        """Drop machine-generated files from a mixed diff.

        Call this *after* ``decide``: a lockfile-only PR should still skip as
        deps-only, and stripping first would leave an empty diff to reason about.
        Returns the diff unchanged when every file is generated, so the caller
        never ends up reviewing nothing.
        """
        if not diff.files:
            return diff, []

        generated = [f for f in diff.files if self.is_generated(f)]
        if not generated:
            return diff, []

        keep = [f for f in diff.files if f not in set(generated)]
        if not keep:
            return diff, []

        return diff.slice_files(keep), generated

    def _is_tests_only(self, diff: ParsedDiff) -> bool:
        if not diff.files:
            return False
        return all(self._matches_any_pattern(f, self.TEST_PATTERNS) for f in diff.files)

    def get_complexity_score(self, diff: ParsedDiff) -> float:
        score = 0.0

        score += min(diff.lines_added / 100, 5)
        score += min(diff.lines_deleted / 100, 5)
        score += min(len(diff.files) / 10, 3)

        for file in diff.files:
            if any(x in file.lower() for x in ["api", "core", "service", "handler"]):
                score += 0.5

        return min(score, 10.0)
